### ISSUE TITLE
build-centos7_maya.sh error

### ISSUE THREAD

**Issue by 1770577032** [AnimalLogic/docker-usd#5]
I try to use this script to build AL_USDMaya.
but I got this error.
Linux localhost.localdomain 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Centos 7,Docker version 18.06.1-ce.**

[root@localhost linux]# ./build-centos7_maya.sh -2017
..........
...........
..........
Successfully built 05b9d9a0e204
Successfully tagged usd-docker/vfx:1-centos7
Build Maya v
Sending build context to Docker daemon  57.86kB
Step 1/10 : FROM usd-docker/vfx:latest-centos7
 ---> 05b9d9a0e204
Step 2/10 : ARG current_host_ip_address
 ---> Using cache
 ---> b02c92a165f1
Step 3/10 : ARG maya_version
 ---> Using cache
 ---> e4faed16398c
Step 4/10 : LABEL maya.version="${maya_version}.0" maintainer="Animal Logic"
 ---> Using cache
 ---> 1c28d7d9fd06
Step 5/10 : ENV MAYA_LOCATION=$BUILD_DIR/maya{maya_version}DevKit
 ---> Using cache
 ---> 060284fdb5a9
Step 6/10 : ENV HTTP_HOSTNAME=$current_host_ip_address
 ---> Using cache
 ---> b5738f466101
Step 7/10 : ENV MAYA_EXECUTABLE=$MAYA_LOCATION/bin/maya
 ---> Using cache
 ---> e617539667ae
Step 8/10 : ENV MAYA_MAJOR_VERSION="${maya_version}"
 ---> Using cache
 ---> 8fe1799b5234
Step 9/10 : COPY scripts/build_maya.sh scripts/download_maya.sh /tmp/
 ---> Using cache
 ---> 1c969dc3e3d4
Step 10/10 : RUN /tmp/download_maya.sh &&     /tmp/build_maya.sh
 ---> Using cache
 ---> d6800c4a7525
Successfully built d6800c4a7525
Successfully tagged usd-docker/maya:1-centos7
Build USD v18.11
Sending build context to Docker daemon  57.86kB
Step 1/15 : ARG maya_version
Step 2/15 : FROM usd-docker/maya${maya_version}:latest-centos7
**pull access denied for usd-docker/maya2017, repository does not exist or may require 'docker login'
./build-centos7_maya.sh: line 26:   300 Terminated              python -m SimpleHTTPServer**

**Comment by aloysbaillet** [comment]
It seems that the download failed without telling why... could you list the content of the ../downloads folder?

**Comment by 1770577032** [comment]
> It seems that the download failed without telling why... could you list the content of the ../downloads folder?

welll...I fix that problem already...But now I got this...



Successfully built d6800c4a7525
Successfully tagged usd-docker/maya:1-centos7
Build USD v18.11
Sending build context to Docker daemon  57.86kB
Step 1/15 : ARG maya_version
Step 2/15 : FROM usd-docker/maya${maya_version}:latest-centos7
**pull access denied for usd-docker/maya2017, repository does not exist or may require 'docker login'
./build-centos7_maya.sh: line 26: 32276 Terminated              python -m SimpleHTTPServer**

**Comment by aloysbaillet** [comment]
Could you send the actual command line you are running?

**Comment by 1770577032** [comment]
> Could you send the actual command line you are running?

./build-centos7_maya.sh

**Comment by 1770577032** [comment]
> Could you send the actual command line you are running?
./build-centos7_maya.sh -2017

**Comment by aloysbaillet** [comment]
you should run `./build-centos7_maya.sh 2017`

**Comment by aloysbaillet** [comment]
Well apologies I found a bad tag indeed, it's fixed in master

**Comment by 1770577032** [comment]
> Well apologies I found a bad tag indeed, it's fixed in master

thx for help.

But I can't use that for now..
I got this error..


Downloading from proxy http: http://192.168.1.120:8000/Maya2017_DEVKIT_Linux.tgz
172.17.0.2 - - [26/Oct/2018 20:08:00] "GET /Maya2017_DEVKIT_Linux.tgz HTTP/1.1" 200 -
**tar: /tmp/usd-downloads/Maya-2017_DEVKIT_Linux.tgz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now**
The command '/bin/sh -c /tmp/download_maya.sh &&     /tmp/build_maya.sh' returned a non-zero code: 2
./build-centos7_maya.sh: line 26:  8696 Terminated              python -m SimpleHTTPServer

**Comment by aloysbaillet** [comment]
I know 2018 is working if you want to try?

**Comment by 1770577032** [comment]
> I know 2018 is working if you want to try?

I try to build 2017..
I have solve that problem ...

Now  I get this error...


**-- Found PySide: True  
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named OpenGL
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find PyOpenGL (missing: PYOPENGL_AVAILABLE)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindPyOpenGL.cmake:43 (find_package_handle_standard_args)
  cmake/defaults/Packages.cmake:137 (find_package)
  CMakeLists.txt:34 (include)**

**Comment by 1770577032** [comment]
[root@localhost linux]# ./build-centos7_maya.sh 2017
Downloads folder: /root/dev/docker-usd/linux/../downloads
Copy local root certificates for corporate networks
Serving HTTP on 0.0.0.0 port 8000 ...
Build base: base centos packages and gcc
Sending build context to Docker daemon  57.86kB
Step 1/16 : ARG cuda_version=latest
Step 2/16 : FROM nvidia/cudagl:${cuda_version}-devel-centos7
 ---> d5b56895d790
Step 3/16 : LABEL maintainer="Aloys.Baillet - Animal Logic"
 ---> Using cache
 ---> 9cba9a4bf6c2
Step 4/16 : ENV BUILD_PROCS 7
 ---> Using cache
 ---> 854e8928c15a
Step 5/16 : ENV BUILD_DIR /opt/usd
 ---> Using cache
 ---> 058ae175b3ce
Step 6/16 : ENV TMP_DIR /tmp/usd-build
 ---> Using cache
 ---> 83884eb6c7fe
Step 7/16 : ENV DOWNLOADS_DIR /tmp/usd-downloads
 ---> Using cache
 ---> 65b51d3dfdc3
Step 8/16 : ENV PATH $BUILD_DIR/bin:$PATH
 ---> Using cache
 ---> 981de7e96c80
Step 9/16 : ENV PKG_CONFIG_PATH=$BUILD_DIR/lib/pkgconfig:$PKG_CONFIG_PATH
 ---> Using cache
 ---> 1d4f747e4ef7
Step 10/16 : ENV LD_LIBRARY_PATH=$BUILD_DIR/lib64:$BUILD_DIR/lib:$LD_LIBRARY_PATH
 ---> Using cache
 ---> 779ce8987d8a
Step 11/16 : RUN yum -y groupinstall "Development Tools"
 ---> Using cache
 ---> 7a29d0750b97
Step 12/16 : RUN yum install -y epel-release && sed -i "s/mirrorlist=https/mirrorlist=http/" /etc/yum.repos.d/epel.repo
 ---> Using cache
 ---> a1f4d37c3b3d
Step 13/16 : RUN yum install -y      wget     openssl-devel     openssl     sqlite-devel     sqlite     glibc-devel.x86_64     libicu-devel    libicu     wget     git     tar     cmake     bzip2     bzip2-devel     glibc-devel.x86_64     glibc-devel.i686     zlib-devel.x86_64     texinfo.x86_64     libXext-devel     openssl-devel     libXext-devel     libXt-devel     libicu-devel     sqlite-devel     tk-devel     ncurses     ncurses-devel     freetype-devel.x86_64     libxml2-devel.x86_64     libxslt-devel.x86_64     mesa-libGL-devel.x86_64     libXrandr-devel.x86_64     libXinerama-devel.x86_64     libXcursor-devel.x86_64     glut-devel     libXmu-devel     libXi-devel     pulseaudio-libs-devel.x86_64     xorg-x11-fonts-Type1     ca-certificates     python-devel     qt-devel     gstreamer-plugins-base     libXp     libXpm     gamin-devel     tcsh     libXp     libXpm     fam     libpng12     libXcomposite     libjpeg     python-pip     qt-devel.x86_64     python-pyside-devel.x86_64     pyside-tools.x86_64
 ---> Using cache
 ---> 74bfdb3ddaa4
Step 14/16 : COPY cert/* /etc/pki/ca-trust/source/anchors/
 ---> Using cache
 ---> 1c130db5098d
Step 15/16 : RUN update-ca-trust force-enable &&     update-ca-trust extract
 ---> Using cache
 ---> d15cdd017ec7
Step 16/16 : CMD bash
 ---> Using cache
 ---> 109a0d31e480
[Warning] One or more build-args [current_host_ip_address] were not consumed
Successfully built 109a0d31e480
Successfully tagged usd-docker/base:1-centos7
Build VFX packages
Sending build context to Docker daemon  57.86kB
Step 1/9 : FROM usd-docker/base:latest-centos7
 ---> 109a0d31e480
Step 2/9 : LABEL maintainer="Aloys.Baillet - Animal Logic"
 ---> Using cache
 ---> e3b2279165cf
Step 3/9 : ARG current_host_ip_address
 ---> Using cache
 ---> 73212e96deb0
Step 4/9 : ENV PYTHON_SITE_PACKAGES=$BUILD_DIR/lib/python2.7/site-packages
 ---> Using cache
 ---> f312280d0ee3
Step 5/9 : ENV PYTHON_EXECUTABLE=python
 ---> Using cache
 ---> f7b9794a574e
Step 6/9 : ENV PYTHONPATH=$PYTHONPATH:/opt/usd/lib/python:/opt/usd/lib/python/site-packages:/opt/usd/lib64/python/site-packages
 ---> Using cache
 ---> 94b96d40e341
Step 7/9 : ENV HTTP_HOSTNAME=$current_host_ip_address
 ---> Using cache
 ---> 06c675dd9031
Step 8/9 : COPY scripts/build_vfx.sh scripts/build_vfx_base.sh scripts/download_vfx.sh /tmp/
 ---> Using cache
 ---> 10fca106954c
Step 9/9 : RUN /tmp/download_vfx.sh &&     /tmp/build_vfx_base.sh &&     /tmp/build_vfx.sh &&     rm -Rf $DOWNLOADS_DIR/*
 ---> Using cache
 ---> 05b9d9a0e204
Successfully built 05b9d9a0e204
Successfully tagged usd-docker/vfx:1-centos7
Build Maya v2017
Sending build context to Docker daemon  57.86kB
Step 1/10 : FROM usd-docker/vfx:latest-centos7
 ---> 05b9d9a0e204
Step 2/10 : ARG current_host_ip_address
 ---> Using cache
 ---> b02c92a165f1
Step 3/10 : ARG maya_version
 ---> Using cache
 ---> e4faed16398c
Step 4/10 : LABEL maya.version="${maya_version}.0" maintainer="Animal Logic"
 ---> Using cache
 ---> 1c28d7d9fd06
Step 5/10 : ENV MAYA_LOCATION=$BUILD_DIR/maya{maya_version}DevKit
 ---> Using cache
 ---> 060284fdb5a9
Step 6/10 : ENV HTTP_HOSTNAME=$current_host_ip_address
 ---> Using cache
 ---> b5738f466101
Step 7/10 : ENV MAYA_EXECUTABLE=$MAYA_LOCATION/bin/maya
 ---> Using cache
 ---> e617539667ae
Step 8/10 : ENV MAYA_MAJOR_VERSION="${maya_version}"
 ---> Using cache
 ---> 8fe1799b5234
Step 9/10 : COPY scripts/build_maya.sh scripts/download_maya.sh /tmp/
 ---> Using cache
 ---> 1c969dc3e3d4
Step 10/10 : RUN /tmp/download_maya.sh &&     /tmp/build_maya.sh
 ---> Using cache
 ---> d6800c4a7525
Successfully built d6800c4a7525
Successfully tagged usd-docker/maya2017:1-centos7
Build USD v18.11
Sending build context to Docker daemon  57.86kB
Step 1/15 : ARG maya_version
Step 2/15 : FROM usd-docker/maya${maya_version}:latest-centos7
 ---> d6800c4a7525
Step 3/15 : ARG usd_version
 ---> Using cache
 ---> 935105b5a817
Step 4/15 : ARG maya_version
 ---> Using cache
 ---> 8563f84b255e
Step 5/15 : ARG current_host_ip_address
 ---> Using cache
 ---> 1bf7593f18dd
Step 6/15 : LABEL pxr.usd.version="${usd_version}" maintainer="Aloys.Baillet - Animal Logic"
 ---> Using cache
 ---> 0d0484795367
Step 7/15 : ENV USD_VERSION="${usd_version}"
 ---> Using cache
 ---> 67cc719ed48b
Step 8/15 : ENV MAYA_MAJOR_VERSION="${maya_version}"
 ---> Using cache
 ---> ba8776b15d10
Step 9/15 : COPY scripts/download_usd.sh scripts/build_usd.sh /tmp/
 ---> Using cache
 ---> a6ed63780dca
Step 10/15 : RUN /tmp/download_usd.sh &&     /tmp/build_usd.sh
 ---> Running in f93e54e94705
Downloading from proxy http: http://192.168.1.120:8000/USD-v18.11.tar.gz
172.17.0.2 - - [26/Oct/2018 20:31:11] "GET /USD-v18.11.tar.gz HTTP/1.1" 200 -
Build USD with Maya 2017
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.5", minimum required is "2.7") 
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found suitable version "2.7.5", minimum required is "2.7") 
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   filesystem
--   program_options
--   python
--   system
-- Found Jinja2
-- Found TBB: /opt/usd/include (found version "4.3") found components:  tbb 
-- Found OpenEXR: /opt/usd/include;/opt/usd/include/OpenEXR  
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found OpenGL: /usr/local/lib64/libGL.so  
-- Found GLEW: /opt/usd/include/GL  
-- Found OpenSubdiv: /opt/usd/include (found suitable version "3.1.0", minimum required is "3") 
-- Found PTex: /opt/usd/include/ptex (found version "2.1.3") 
-- Found PySide: with /usr/bin/python2.7, will use /usr/bin/pyside-uic for pyside-uic binary
-- Found PySide: True  
**Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named OpenGL
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find PyOpenGL (missing: PYOPENGL_AVAILABLE)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindPyOpenGL.cmake:43 (find_package_handle_standard_args)
  cmake/defaults/Packages.cmake:137 (find_package)
  CMakeLists.txt:34 (include)


-- Configuring incomplete, errors occurred!**
See also "/tmp/usd-build/USD-18.11/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/usd-build/USD-18.11/build/CMakeFiles/CMakeError.log".
The command '/bin/sh -c /tmp/download_usd.sh &&     /tmp/build_usd.sh' returned a non-zero code: 1
./build-centos7_maya.sh: line 26: 14749 Terminated              python -m SimpleHTTPServer
